feat: подготовил структуру проекта, создал контроллёры, dto, написал …
RoketV/java-filmorate pull request #1
Opened 2022-10-12 13:18 UTC by RoketV

…тесты и ввёл базовую функциональность

2022-10-12 14:01 UTC, RoketV commented
Подготовил структуру проекта, контролеры, тесты, dto

2022-10-12 20:25 UTC, andrew-larkin requested changes
Привет! Очень качественная реализация, ты добавил уровень сервисов и dto, оформил валидацию как следует, написал хорошие тесты. Остается небольшой рефакторинг и мы будем готовы двигаться дальше.

2022-10-12 20:25 UTC, andrew-larkin commented on filmorate/src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
аналогичные правки как и в FilmController

2022-10-12 20:25 UTC, andrew-larkin commented on filmorate/src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +public class FilmDto {
на самом деле все ограничения валидации лучше перенести на классы моделей, потому что именно там эта проверка должна осуществляться. DTO используются, как правило, лишь для передачи информации из приложения на сервер и обратно

2022-10-14 13:45 UTC, RoketV commented on filmorate/src/main/java/ru/yandex/practicum/filmorate/dto/FilmDto.java
> +public class FilmDto {
Всё сделал, как ты и сказал кроме переноса валидации из dto в model. Поговорил с наставником, он сказал, что валидировать можно и через dto, так как это проверка входящий данных идёт сразу. Но если нужно, я уберу валидацию из dto и перенесу в models.

2022-10-18 16:21 UTC, merged